version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - ./init:/var/lib/neo4j/conf
    ports:
      - 7474:7474
      - 7687:7687