-- Petclinic schema for Oracle — tables, views, functions, procedures, package, trigger
-- Run as SYSTEM in FREEPDB1. Idempotent: drops existing objects before recreating.

SET DEFINE OFF
SET ECHO OFF
WHENEVER SQLERROR CONTINUE

-- ── Drop existing objects (reverse dependency order) ─────────────────────────

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE BODY PET_PKG';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PET_PKG';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_VISIT_AUDIT';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_MERGE_OWNER';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_TRANSFER_PET'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_ADD_VISIT';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FUNC_OWNER_PET_COUNT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FUNC_COUNT_VISITS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_VET_SPECIALTIES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_OWNER_PETS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VISITS          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VET_SPECIALTIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PETS            CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TYPES           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SPECIALTIES     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VETS            CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OWNERS          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE OWNERS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(30)  NOT NULL,
    LAST_NAME  VARCHAR2(30)  NOT NULL,
    ADDRESS    VARCHAR2(255),
    CITY       VARCHAR2(80),
    TELEPHONE  VARCHAR2(20)
);

CREATE TABLE TYPES (
    ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(80) NOT NULL
);

CREATE TABLE PETS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME       VARCHAR2(30)  NOT NULL,
    BIRTH_DATE DATE,
    TYPE_ID    NUMBER        NOT NULL,
    OWNER_ID   NUMBER        NOT NULL,
    CONSTRAINT FK_PET_TYPE  FOREIGN KEY (TYPE_ID)  REFERENCES TYPES(ID),
    CONSTRAINT FK_PET_OWNER FOREIGN KEY (OWNER_ID) REFERENCES OWNERS(ID)
);

CREATE TABLE VETS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(30) NOT NULL,
    LAST_NAME  VARCHAR2(30) NOT NULL
);

CREATE TABLE SPECIALTIES (
    ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(80) NOT NULL
);

CREATE TABLE VET_SPECIALTIES (
    VET_ID       NUMBER NOT NULL,
    SPECIALTY_ID NUMBER NOT NULL,
    CONSTRAINT PK_VET_SPEC     PRIMARY KEY (VET_ID, SPECIALTY_ID),
    CONSTRAINT FK_VS_VET       FOREIGN KEY (VET_ID)       REFERENCES VETS(ID),
    CONSTRAINT FK_VS_SPECIALTY FOREIGN KEY (SPECIALTY_ID) REFERENCES SPECIALTIES(ID)
);

CREATE TABLE VISITS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PET_ID      NUMBER       NOT NULL,
    VISIT_DATE  DATE         DEFAULT SYSDATE NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CONSTRAINT FK_VISIT_PET FOREIGN KEY (PET_ID) REFERENCES PETS(ID)
);

-- ── Views ─────────────────────────────────────────────────────────────────────

-- Owner + pets summary (joins OWNERS, PETS, TYPES)
CREATE OR REPLACE VIEW V_OWNER_PETS AS
SELECT o.ID        AS OWNER_ID,
       o.FIRST_NAME,
       o.LAST_NAME,
       p.ID        AS PET_ID,
       p.NAME      AS PET_NAME,
       p.BIRTH_DATE,
       t.NAME      AS PET_TYPE
FROM   OWNERS o
JOIN   PETS   p ON p.OWNER_ID = o.ID
JOIN   TYPES  t ON t.ID       = p.TYPE_ID;

-- Vet + specialties (joins VETS, VET_SPECIALTIES, SPECIALTIES)
CREATE OR REPLACE VIEW V_VET_SPECIALTIES AS
SELECT v.ID         AS VET_ID,
       v.FIRST_NAME,
       v.LAST_NAME,
       s.NAME       AS SPECIALTY
FROM   VETS            v
JOIN   VET_SPECIALTIES vs ON vs.VET_ID      = v.ID
JOIN   SPECIALTIES     s  ON s.ID           = vs.SPECIALTY_ID;

-- ── Functions ─────────────────────────────────────────────────────────────────

-- Count visits for a given pet
CREATE OR REPLACE FUNCTION FUNC_COUNT_VISITS (p_pet_id IN NUMBER)
RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM VISITS WHERE PET_ID = p_pet_id;
    RETURN v_count;
END FUNC_COUNT_VISITS;
/

-- Count pets for a given owner
CREATE OR REPLACE FUNCTION FUNC_OWNER_PET_COUNT (p_owner_id IN NUMBER)
RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM PETS WHERE OWNER_ID = p_owner_id;
    RETURN v_count;
END FUNC_OWNER_PET_COUNT;
/

-- ── Procedures ────────────────────────────────────────────────────────────────

-- Register a new visit for a pet
CREATE OR REPLACE PROCEDURE PROC_ADD_VISIT (
    p_pet_id      IN NUMBER,
    p_date        IN DATE,
    p_description IN VARCHAR2
) AS
BEGIN
    INSERT INTO VISITS (PET_ID, VISIT_DATE, DESCRIPTION)
    VALUES (p_pet_id, p_date, p_description);
    COMMIT;
END PROC_ADD_VISIT;
/

-- Transfer a pet to a different owner
CREATE OR REPLACE PROCEDURE PROC_TRANSFER_PET (
    p_pet_id       IN NUMBER,
    p_new_owner_id IN NUMBER
) AS
BEGIN
    UPDATE PETS SET OWNER_ID = p_new_owner_id WHERE ID = p_pet_id;
    COMMIT;
END PROC_TRANSFER_PET;
/

-- Upsert an owner by name (insert if not exists)
CREATE OR REPLACE PROCEDURE PROC_MERGE_OWNER (
    p_first_name IN VARCHAR2,
    p_last_name  IN VARCHAR2,
    p_address    IN VARCHAR2,
    p_city       IN VARCHAR2,
    p_telephone  IN VARCHAR2
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM   OWNERS
    WHERE  FIRST_NAME = p_first_name AND LAST_NAME = p_last_name;

    IF v_count = 0 THEN
        INSERT INTO OWNERS (FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
        VALUES (p_first_name, p_last_name, p_address, p_city, p_telephone);
        COMMIT;
    END IF;
END PROC_MERGE_OWNER;
/

-- ── Package ───────────────────────────────────────────────────────────────────

CREATE OR REPLACE PACKAGE PET_PKG AS
    -- Returns number of pets for an owner
    FUNCTION  GET_PET_COUNT   (p_owner_id IN NUMBER) RETURN NUMBER;
    -- Returns number of visits for a pet (delegates to FUNC_COUNT_VISITS)
    FUNCTION  GET_VISIT_COUNT (p_pet_id   IN NUMBER) RETURN NUMBER;
    -- Registers a visit using today's date (delegates to PROC_ADD_VISIT)
    PROCEDURE REGISTER_VISIT  (p_pet_id   IN NUMBER, p_desc IN VARCHAR2);
    -- Archives a pet: appends _ARCHIVED to name after logging visit count
    PROCEDURE ARCHIVE_PET     (p_pet_id   IN NUMBER);
END PET_PKG;
/

CREATE OR REPLACE PACKAGE BODY PET_PKG AS

    FUNCTION GET_PET_COUNT (p_owner_id IN NUMBER) RETURN NUMBER AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM PETS WHERE OWNER_ID = p_owner_id;
        RETURN v_count;
    END GET_PET_COUNT;

    FUNCTION GET_VISIT_COUNT (p_pet_id IN NUMBER) RETURN NUMBER AS
    BEGIN
        RETURN FUNC_COUNT_VISITS(p_pet_id);   -- CALLS FUNC_COUNT_VISITS
    END GET_VISIT_COUNT;

    PROCEDURE REGISTER_VISIT (p_pet_id IN NUMBER, p_desc IN VARCHAR2) AS
    BEGIN
        PROC_ADD_VISIT(p_pet_id, SYSDATE, p_desc);   -- CALLS PROC_ADD_VISIT
    END REGISTER_VISIT;

    PROCEDURE ARCHIVE_PET (p_pet_id IN NUMBER) AS
        v_visits NUMBER;
    BEGIN
        v_visits := FUNC_COUNT_VISITS(p_pet_id);     -- CALLS FUNC_COUNT_VISITS
        UPDATE PETS SET NAME = NAME || '_ARCHIVED' WHERE ID = p_pet_id;
        COMMIT;
    END ARCHIVE_PET;

END PET_PKG;
/

-- ── Trigger ───────────────────────────────────────────────────────────────────

-- Audit trigger: fires after every insert on VISITS
CREATE OR REPLACE TRIGGER TRG_VISIT_AUDIT
AFTER INSERT ON VISITS
FOR EACH ROW
BEGIN
    NULL;  -- placeholder; dependency on VISITS captured by DBA_DEPENDENCIES
END TRG_VISIT_AUDIT;
/

COMMIT;
EXIT;
